apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: book2go
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: gabrieleban/catalog-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/b2g_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: AUTH_SERVICE_INTERNAL_URL
              value: "http://auth-service:8090"
            - name: AUTH_SERVICE_JWKS_URL
              value: "http://auth-service:8090/auth/.well-known/jwks.json"