apiVersion: apps/v1
kind: Deployment
metadata:
  name: lend-service
  namespace: book2go
  labels:
    app: lend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lend-service
  template:
    metadata:
      labels:
        app: lend-service
    spec:
      containers:
        - name: lend-service
          image: gabrieleban/lend-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8099
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/b2g_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"