apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: book2go
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NEO4J_PASSWORD
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-pvc
        - name: neo4j-logs
          persistentVolumeClaim:
            claimName: neo4j-logs-pvc