apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-service
  namespace: book2go
  labels:
    app: reader-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader-service
  template:
    metadata:
      labels:
        app: reader-service
    spec:
      containers:
        - name: reader-service
          image: gabrieleban/reader-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8098
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SERVER_PORT
              value: "8098"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/b2g_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: MINIO_URL
              value: "http://minio:9000"
            - name: AUTH_SERVICE_INTERNAL_URL
              value: "http://auth-service:8090"
            - name: AUTH_SERVICE_JWKS_URL
              value: "http://auth-service:8090/auth/.well-known/jwks.json"