apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: book2go
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8097
      targetPort: 8097
  type: ClusterIP